### ISSUE TITLE
Voting without enough balance

### ISSUE THREAD

**Issue by jerkyrs** [iost-official/go-iost#833]
Attempt to vote for a producer without enough balance to cast that vote

```
iwallet --account metanyx system vote metanyx 99999
```

Error is unhandled stack trace
```
running action Action{Contract: vote_producer.iost, ActionName: vote, Data: ["metanyx","metanyx","99999"]}
 error: Uncaught exception: Error: Uncaught exception: Error: balance not enough 1111.09 < 99999
at blockchain.js:21:29
          return JSON.parse(bc.callWithAuth("token.iost", "transfer", JSON.stringify(args)));
                               ^
Stack tree: 
Error: balance not enough 1111.09 < 99999
    at transfer (blockchain.js:21:30)
    at Object.deposit (blockchain.js:32:20)
    at VoteCommonContract.voteFor (_default_name.js:329:54)
    at VoteCommonContract.vote (_default_name.js:360:47)
    at _default_name.js:477:14
at blockchain.js:66:33
              return JSON.parse(bc.callWithAuth(contract, api, args));
                                   ^
Stack tree: 
Error: Uncaught exception: Error: balance not enough 1111.09 < 99999
at blockchain.js:21:29
          return JSON.parse(bc.callWithAuth("token.iost", "transfer", JSON.stringify(args)));
                               ^
Stack tree: 
Error: balance not enough 1111.09 < 99999
    at transfer (blockchain.js:21:30)
    at Object.deposit (blockchain.js:32:20)
    at VoteCommonContract.voteFor (_default_name.js:329:54)
    at VoteCommonContract.vote (_default_name.js:360:47)
    at _default_name.js:477:14
    at Object.callWithAuth (blockchain.js:66:34)
    at VoteContract.vote (_default_name.js:547:70)
    at _default_name.js:825:14
```

This should be handled gracefully

**Comment by jerkyrs** [comment]
Error persists on 3.0.7

```
Stack tree:
Error: balance not enough 0 < 100
    at transfer (blockchain.js:21:30)
    at Object.deposit (blockchain.js:32:20)
    at VoteCommonContract.voteFor (_default_name.js:342:54)
    at VoteCommonContract.vote (_default_name.js:372:47)
    at _default_name.js:490:14
at blockchain.js:66:33
              return JSON.parse(bc.callWithAuth(contract, api, args));
                                   ^
Stack tree:
Error: Uncaught exception: Error: balance not enough 0 < 100
at blockchain.js:21:29
          return JSON.parse(bc.callWithAuth("token.iost", "transfer", JSON.stringify(args)));
                               ^
Stack tree:
Error: balance not enough 0 < 100
    at transfer (blockchain.js:21:30)
    at Object.deposit (blockchain.js:32:20)
    at VoteCommonContract.voteFor (_default_name.js:342:54)
    at VoteCommonContract.vote (_default_name.js:372:47)
    at _default_name.js:490:14
    at Object.callWithAuth (blockchain.js:66:34)
    at VoteContract.vote (_default_name.js:514:70)
    at _default_name.js:855:14
```
