### ISSUE TITLE
unregister a producer that doesnt exist uncaught exception

### ISSUE THREAD

**Issue by jerkyrs** [iost-official/go-iost#835]
unregister a producer who that is not registered

command
```
iwallet --account jerkyrs  system unregister HyzGVMTTbo6N3hYhaQdFV7kpMMTNeookmjXXy2MmZLy
```

Error
```
exec tx failed:  running action Action{Contract: vote_producer.iost, ActionName: applyUnregister, Data: ["jerkyrs"]}
 error: Uncaught exception: Error: producer not exists
at _default_name.js:170:48
              _IOSTInstruction_counter.incr(61.9);throw new Error('producer not exists');
                                                  ^
Stack tree: 
Error: producer not exists
    at VoteContract.applyUnregister (_default_name.js:170:55)
    at _default_name.js:825:14
full error information:  {
    "txHash": "85A2vrnokBhwsPZY8cRGNRXd13XMeD1kuWjXZpsY2mRH",
    "gasUsage": 34299,
    "ramUsage": {
    },
    "statusCode": "RUNTIME_ERROR",
    "message": "running action Action{Contract: vote_producer.iost, ActionName: applyUnregister, Data: [\"jerkyrs\"]}\n error: Uncaught exception: Error: producer not exists\nat _default_name.js:170:48\n              _IOSTInstruction_counter.incr(61.9);throw new Error('producer not exists');\n                                                  ^\nStack tree: \nError: producer not exists\n    at VoteContract.applyUnregister (_default_name.js:170:55)\n    at _default_name.js:825:14",
    "returns": [
    ],
    "receipts": [
    ]
}
running action Action{Contract: vote_producer.iost, ActionName: applyUnregister, Data: ["jerkyrs"]}
 error: Uncaught exception: Error: producer not exists
at _default_name.js:170:48
              _IOSTInstruction_counter.incr(61.9);throw new Error('producer not exists');
                                                  ^
Stack tree: 
Error: producer not exists
    at VoteContract.applyUnregister (_default_name.js:170:55)
    at _default_name.js:825:14
```

**Comment by jerkyrs** [comment]
as only one producer should only ever be registered per account you should be able to run this without specifying a public key (as its already know)

```
iwallet --account jerkyrs sys unregister  
```

This throws error to (without a registered producer and not declaring public key as i did above)
