### ISSUE TITLE
re-registering a producer option already exist

### ISSUE THREAD

**Issue by jerkyrs** [iost-official/go-iost#836]
1. Register producer
2. Unregister producer
3. register same or new producer

It appears you can not register, unregister and re-register the same or a new producer
```
full error information:  {
    "txHash": "FduEFM6ySYdbwJieUgi2Arg4WBoFot6ZPVnc2M9kVxsk",
    "gasUsage": 71856,
    "ramUsage": {
    },
    "statusCode": "RUNTIME_ERROR",
    "message": "running action Action{Contract: vote_producer.iost, ActionName: applyRegister, Data: [\"jerkyrs\",\"HyzGVMTTbo6N3hYhaQ... error: Uncaught exception: Error: Uncaught exception: Error: option already exist.\nat _default_name.js:228:52\n                  _IOSTInstruction_counter.incr(62.1);throw new Error('option already exist.');\n                                                      ^\nStack tree: \nError: option already exist.\n    at VoteCommonContract.addOption (_default_name.js:228:59)\n    at _default_name.js:477:14\nat blockchain.js:66:33\n              return JSON.parse(bc.callWithAuth(contract, api, args));\n                                   ^\nStack tree: \nError: Uncaught exception: Error: option already exist.\nat _default_name.js:228:52\n                  _IOSTInstruction_counter.incr(62.1);throw new Error('option already exist.');\n                                                      ^\nStack tree: \nError: option already exist.\n    at VoteCommonContract.addOption (_default_name.js:228:59)\n    at _default_name.js:477:14\n    at Object.callWithAuth (blockchain.js:66:34)\n    at VoteContract.applyRegister (_default_name.js:161:56)\n    at _default_name.js:825:14",
    "returns": [
    ],
    "receipts": [
    ]
}
running action Action{Contract: vote_producer.iost, ActionName: applyRegister, Data: ["jerkyrs","HyzGVMTTbo6N3hYhaQ... error: Uncaught exception: Error: Uncaught exception: Error: option already exist.
at _default_name.js:228:52
                  _IOSTInstruction_counter.incr(62.1);throw new Error('option already exist.');
                                                      ^
Stack tree: 
Error: option already exist.
    at VoteCommonContract.addOption (_default_name.js:228:59)
    at _default_name.js:477:14
at blockchain.js:66:33
              return JSON.parse(bc.callWithAuth(contract, api, args));
                                   ^
Stack tree: 
Error: Uncaught exception: Error: option already exist.
at _default_name.js:228:52
                  _IOSTInstruction_counter.incr(62.1);throw new Error('option already exist.');
                                                      ^
Stack tree: 
Error: option already exist.
    at VoteCommonContract.addOption (_default_name.js:228:59)
    at _default_name.js:477:14
    at Object.callWithAuth (blockchain.js:66:34)
    at VoteContract.applyRegister (_default_name.js:161:56)
    at _default_name.js:825:14
```

If no producers are registered to a user they should be able to register a new one ,  if there is delay between operations the request should be handled gracefully

**Comment by jerkyrs** [comment]
seems like you can now use the following

```
iwallet sys producer-clean
```

However if you run this without an account who has a producer you get the following on 3.0.7

```
 error: Uncaught exception: Error: Uncaught exception: Error: option not exist
at _default_name.js:261:48
              _IOSTInstruction_counter.incr(61.6);throw new Error('option not exist');
                                                  ^
Stack tree:
Error: option not exist
    at VoteCommonContract.removeOption (_default_name.js:261:55)
    at _default_name.js:490:14
at blockchain.js:66:33
              return JSON.parse(bc.callWithAuth(contract, api, args));
                                   ^
Stack tree:
Error: Uncaught exception: Error: option not exist
at _default_name.js:261:48
              _IOSTInstruction_counter.incr(61.6);throw new Error('option not exist');
                                                  ^
Stack tree:
Error: option not exist
    at VoteCommonContract.removeOption (_default_name.js:261:55)
    at _default_name.js:490:14
    at Object.callWithAuth (blockchain.js:66:34)
    at VoteContract.unregister (_default_name.js:246:70)
    at _default_name.js:855:14
```

This should be handled gracefully
